export const API_URL = 'https://mbsapidev.azurewebsites.net/api' // Azure : https://mbsapidev.azurewebsites.net/api  local: https://localhost:7002/api
// export const API_URL = ' https://localhost:7002/api'
export const URL = {
  LOGIN: API_URL + '/Account/login',
  REGISTER: API_URL + '/auth/signup',

  COUNTRY: API_URL + '/Countries',
  PROJECT: API_URL + '/Projects',
  PROJECT_CATEGORIES: API_URL + '/ProjectCategories',
  PROJECT_SUBCATEGORIES: API_URL + '/ProjectSubCategories',
  INFRA_CHECKLIST: API_URL + '/TblInfrastructures',
  GENERAL_EQUIPMENT: API_URL + '/EquipmentModel',
  PROJECT_REPRESENTATION: API_URL + '/ProjectRepresentation',

  ROSTER: API_URL + '/Roosters',
  CONSTANT: API_URL + '/Constants',
  LEVY_CATEGORIES: API_URL + '/Levycategory',
  LEVIES: API_URL + '/Levy',

  COST_INDICES: API_URL + '/FinancialDataCostIndiciesSchedule',
  EXCHANGE_RATE: API_URL + '/FinancialDataExchangeRateSchedule',
  MATERIALS: API_URL + '/Resources',
  EMPLOYEE_TYPE: API_URL + '/EmployeeType',
  FLEETS: API_URL + '/Fleets',
  FLEETCOSTCOMPONENT: API_URL + '/FleetCostComponent',
  FLEETSPAREPART: API_URL + '/FleetSparePart',
  FLEETMATERIALSERVICE: API_URL + '/FleetMaterialService',
  FLEETMATERIALSERVICESCHEDULE: API_URL + '/FleetMaterialServiceSchedule',
  FLEETOPERATORS: API_URL + '/FleetOperators',
  RESOURCES_INFRA: API_URL + '/ResourceInfrastructure',
  EQUIPMENTCC: API_URL + '/CostCentreStructureEquipment',
  PERSONELCC: API_URL + '/CostCentreStructurePersonel',
  MATERIALCC: API_URL + '/CostCentreStructureMaterial',
  INFRASTRUCTURECC: API_URL + '/CostCentreStructureInfrastructure',
  COSTCENTRE: API_URL + '/CostCentre',
  EQUIPMENTSCHEDULEOH: API_URL + '/EquipmentSchedule',
  EQUIPMENTSCHEDULEPA: API_URL + '/EquipmentSchedulePA',
  EQUIPMENTROSTER: API_URL + '/EquipmentScheduleRoster',
  ACCOUNT: API_URL + '/Account',
  COMPANY: API_URL + '/CompanySource',
  USERS: API_URL + '/Users',
  PRODUCTION_FACTOR: API_URL + '/ProductionFactor',
  PRODUCTION_SCHEDULE: API_URL + '/ProductionSchedule',
}

export const HANDLE_LOGIN = 'HANDLE_LOGIN'
export const HANDLE_LOGIN_SUCCESS = 'HANDLE_LOGIN_SUCCESS'
export const HANDLE_LOGIN_ERROR = 'HANDLE_LOGIN_ERROR'

export const HANDLE_REGISTER = 'HANDLE_REGISTER'

export const GET_PROJECT_CATEGORIES = 'GET_PROJECT_CATEGORIES'
export const GET_PROJECT_CATEGORIES_SUCCESS = 'GET_PROJECT_CATEGORIES_SUCCESS'
export const GET_PROJECT_CATEGORIES_ERROR = 'GET_PROJECT_CATEGORIES_ERROR'

export const GET_PROJECT_SUBCATEGORIES = 'GET_PROJECT_SUBCATEGORIES'
export const GET_PROJECT_SUBCATEGORIES_SUCCESS = 'GET_PROJECT_SUBCATEGORIES_SUCCESS'
export const GET_PROJECT_SUBCATEGORIES_ERROR = 'GET_PROJECT_SUBCATEGORIES_ERROR'

export const GET_PROJECT_SUBCATEGORY_BY_CATEGORYID = 'GET_PROJECT_SUBCATEGORY_BY_CATEGORYID'
export const GET_PROJECT_SUBCATEGORY_BY_CATEGORYID_SUCCESS =
  'GET_PROJECT_SUBCATEGORY_BY_CATEGORYID_SUCCESS'
export const GET_PROJECT_SUBCATEGORY_BY_CATEGORYID_ERROR =
  'GET_PROJECT_SUBCATEGORY_BY_CATEGORYID_ERROR'

export const GET_PROJECT_COUNTRY = 'GET_PROJECT_COUNTRY'
export const GET_PROJECT_COUNTRY_SUCCESS = 'GET_PROJECT_COUNTRY_SUCCESS'
export const GET_PROJECT_COUNTRY_ERROR = 'GET_PROJECT_COUNTRY_ERROR'

export const POST_PROJECT = 'POST_PROJECT'
export const POST_PROJECT_SUCCESS = 'POST_PROJECT_SUCCESS'
export const POST_PROJECT_ERROR = 'POST_PROJECT_ERROR'

export const GET_PROJECT = 'GET_PROJECT'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR'

export const GET_PROJECT_DASHBOARD = 'GET_PROJECT_DASHBOARD'
export const GET_PROJECT_DASHBOARD_SUCCESS = 'GET_PROJECT_DASHBOARD_SUCCESS'
export const GET_PROJECT_DASHBOARD_ERROR = 'GET_PROJECT_DASHBOARD_ERROR'

export const GET_DROPDOWN_PROJECT = 'GET_DROPDOWN_PROJECT'
export const GET_DROPDOWN_PROJECT_SUCCESS = 'GET_DROPDOWN_PROJECT_SUCCESS'
export const GET_DROPDOWN_PROJECT_ERROR = 'GET_DROPDOWN_PROJECT_ERROR'

export const PUT_PROJECT = 'PUT_PROJECT'
export const PUT_PROJECT_SUCCESS = 'PUT_PROJECT_SUCCESS'
export const PUT_PROJECT_ERROR = 'PUT_PROJECT_ERROR'

export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_ERROR = 'DELETE_PROJECT_ERROR'

export const GET_LIST_PROJECT_CATEGORIES = 'GET_LIST_PROJECT_CATEGORIES'
export const GET_LIST_PROJECT_CATEGORIES_SUCCESS = 'GET_LIST_PROJECT_CATEGORIES_SUCCESS'
export const GET_LIST_PROJECT_CATEGORIES_ERROR = 'GET_LIST_PROJECT_CATEGORIES_ERROR'

export const POST_PROJECT_CATEGORIES = 'POST_PROJECT_CATEGORIES'
export const POST_PROJECT_CATEGORIES_SUCCESS = 'POST_PROJECT_CATEGORIES_SUCCESS'
export const POST_PROJECT_CATEGORIES_ERROR = 'POST_PROJECT_CATEGORIES_ERROR'

export const PUT_PROJECT_CATEGORIES = 'PUT_PROJECT_CATEGORIES'
export const PUT_PROJECT_CATEGORIES_SUCCESS = 'PUT_PROJECT_CATEGORIES_SUCCESS'
export const PUT_PROJECT_CATEGORIES_ERROR = 'PUT_PROJECT_CATEGORIES_ERROR'

export const DELETE_PROJECT_CATEGORIES = 'DELETE_PROJECT_CATEGORIES'
export const DELETE_PROJECT_CATEGORIES_SUCCESS = 'DELETE_PROJECT_CATEGORIES_SUCCESS'
export const DELETE_PROJECT_CATEGORIES_ERROR = 'DELETE_PROJECT_CATEGORIES_ERROR'

export const POST_PROJECT_SUBCATEGORIES = 'POST_PROJECT_SUBCATEGORIES'
export const POST_PROJECT_SUBCATEGORIES_SUCCESS = 'POST_PROJECT_SUBCATEGORIES_SUCCESS'
export const POST_PROJECT_SUBCATEGORIES_ERROR = 'POST_PROJECT_SUBCATEGORIES_ERROR'

export const PUT_PROJECT_SUBCATEGORIES = 'PUT_PROJECT_SUBCATEGORIES'
export const PUT_PROJECT_SUBCATEGORIES_SUCCESS = 'PUT_PROJECT_SUBCATEGORIES_SUCCESS'
export const PUT_PROJECT_SUBCATEGORIES_ERROR = 'PUT_PROJECT_SUBCATEGORIES_ERROR'

export const DELETE_PROJECT_SUBCATEGORIES = 'DELETE_PROJECT_SUBCATEGORIES'
export const DELETE_PROJECT_SUBCATEGORIES_SUCCESS = 'DELETE_PROJECT_SUBCATEGORIES_SUCCESS'
export const DELETE_PROJECT_SUBCATEGORIES_ERROR = 'DELETE_PROJECT_SUBCATEGORIES_ERROR'

export const GET_INFRA_CHECKLIST = 'GET_INFRA_CHECKLIST'
export const GET_INFRA_CHECKLIST_SUCCESS = 'GET_INFRA_CHECKLIST_SUCCESS'
export const GET_INFRA_CHECKLIST_ERROR = 'GET_INFRA_CHECKLIST_ERROR'

export const POST_INFRA_CHECKLIST = 'POST_INFRA_CHECKLIST'
export const POST_INFRA_CHECKLIST_SUCCESS = 'POST_INFRA_CHECKLIST_SUCCESS'
export const POST_INFRA_CHECKLIST_ERROR = 'POST_INFRA_CHECKLIST_ERROR'

export const PUT_INFRA_CHECKLIST = 'PUT_INFRA_CHECKLIST'
export const PUT_INFRA_CHECKLIST_SUCCESS = 'PUT_INFRA_CHECKLIST_SUCCESS'
export const PUT_INFRA_CHECKLIST_ERROR = 'PUT_INFRA_CHECKLIST_ERROR'

export const DELETE_INFRA_CHECKLIST = 'DELETE_INFRA_CHECKLIST'
export const DELETE_INFRA_CHECKLIST_SUCCESS = 'DELETE_INFRA_CHECKLIST_SUCCESS'
export const DELETE_INFRA_CHECKLIST_ERROR = 'DELETE_INFRA_CHECKLIST_ERROR'

export const GET_GENERAL_EQUIPMENT = 'GET_GENERAL_EQUIPMENT'
export const GET_GENERAL_EQUIPMENT_SUCCESS = 'GET_GENERAL_EQUIPMENT_SUCCESS'
export const GET_GENERAL_EQUIPMENT_ERROR = 'GET_GENERAL_EQUIPMENT_ERROR'

export const GET_GENERAL_EQUIPMENT_TYPE = 'GET_GENERAL_EQUIPMENT_TYPE'
export const UPDATE_GENERAL_EQUIPMENT_TYPE = 'UPDATE_GENERAL_EQUIPMENT_TYPE'

export const POST_GENERAL_EQUIPMENT = 'POST_GENERAL_EQUIPMENT'
export const POST_GENERAL_EQUIPMENT_SUCCESS = 'POST_GENERAL_EQUIPMENT_SUCCESS'
export const POST_GENERAL_EQUIPMENT_ERROR = 'POST_GENERAL_EQUIPMENT_ERROR'

export const PUT_GENERAL_EQUIPMENT = 'PUT_GENERAL_EQUIPMENT'
export const PUT_GENERAL_EQUIPMENT_SUCCESS = 'PUT_GENERAL_EQUIPMENT_SUCCESS'
export const PUT_GENERAL_EQUIPMENT_ERROR = 'PUT_GENERAL_EQUIPMENT_ERROR'

export const DELETE_GENERAL_EQUIPMENT = 'DELETE_GENERAL_EQUIPMENT'
export const DELETE_GENERAL_EQUIPMENT_SUCCESS = 'DELETE_GENERAL_EQUIPMENT_SUCCESS'
export const DELETE_GENERAL_EQUIPMENT_ERROR = 'DELETE_GENERAL_EQUIPMENT_ERROR'

export const GET_CURRENCIES = 'GET_CURRENCIES'
export const GET_CURRENCIES_SUCCESS = 'GET_CURRENCIES_SUCCESS'
export const GET_CURRENCIES_ERROR = 'GET_CURRENCIES_ERROR'
export const GET_COUNTRIESCURRENCIES = 'GET_COUNTRIESCURRENCIES'
export const GET_COUNTRIESCURRENCIES_SUCCESS = 'GET_COUNTRIESCURRENCIES_SUCCESS'
export const GET_COUNTRIESCURRENCIES_ERROR = 'GET_COUNTRIESCURRENCIES_ERROR'

export const POST_CURRENCIES = 'POST_CURRENCIES'
export const POST_CURRENCIES_SUCCESS = 'POST_CURRENCIES_SUCCESS'
export const POST_CURRENCIES_ERROR = 'POST_CURRENCIES_ERROR'

export const PUT_CURRENCIES = 'PUT_CURRENCIES'
export const PUT_CURRENCIES_SUCCESS = 'PUT_CURRENCIES_SUCCESS'
export const PUT_CURRENCIES_ERROR = 'PUT_CURRENCIES_ERROR'

export const DELETE_CURRENCIES = 'DELETE_CURRENCIES'
export const DELETE_CURRENCIES_SUCCESS = 'DELETE_CURRENCIES_SUCCESS'
export const DELETE_CURRENCIES_ERROR = 'DELETE_CURRECIES_ERROR'

export const GET_PERIOD = 'GET_PERIOD'
export const GET_PROJECT_REPRESENTATION = 'GET_PROJECT_REPRESENTATION'
export const GET_PROJECT_REPRESENTATION_SUCCESS = 'GET_PROJECT_REPRESENTATION_SUCCESS'
export const GET_PROJECT_REPRESENTATION_ERROR = 'GET_PROJECT_REPRESENTATION_ERROR'

export const RESET_PROJECT_REPRESENTATION = 'RESET_PROJECT_REPRESENTATION'
export const RESET_PROJECT_REPRESENTATION_ERROR = 'RESET_PROJECT_REPRESENTATION_ERROR'

export const POST_PROJECT_REPRESENTATION = 'POST_PROJECT_REPRESENTATION'
export const POST_PROJECT_REPRESENTATION_SUCCESS = 'POST_PROJECT_REPRESENTATION_SUCCESS'
export const POST_PROJECT_REPRESENTATION_ERROR = 'POST_PROJECT_REPRESENTATION_ERROR'

export const PUT_PROJECT_REPRESENTATION = 'PUT_PROJECT_REPRESENTATION'
export const PUT_PROJECT_REPRESENTATION_SUCCESS = 'PUT_PROJECT_REPRESENTATION_SUCCESS'
export const PUT_PROJECT_REPRESENTATION_ERROR = 'PUT_PROJECT_REPRESENTATION_ERROR'

export const DELETE_PROJECT_REPRESENTATION = 'DELETE_PROJECT_REPRESENTATION'
export const DELETE_PROJECT_REPRESENTATION_SUCCESS = 'DELETE_PROJECT_REPRESENTATION_SUCCESS'
export const DELETE_PROJECT_REPRESENTATION_ERROR = 'DELETE_PROJECT_REPRESENTATION_ERROR'

export const GET_PROJECT_REPRESENTATION_DETAIL = 'GET_PROJECT_REPRESENTATION_DETAIL'
export const GET_PROJECT_REPRESENTATION_DETAIL_SUCCESS = 'GET_PROJECT_REPRESENTATION_DETAIL_SUCCESS'
export const GET_PROJECT_REPRESENTATION_DETAIL_ERROR = 'GET_PROJECT_REPRESENTATION_DETAIL_ERROR'

export const SET_PROJECT = 'SET_PROJECT'
export const SET_PROJECT_REPRESENTATION = 'SET_PROJECT_REPRESENTATION'
export const SET_PROJECT_ERROR = 'SET_PROJECT_ERROR'
export const SET_PROJECT_REPRESENTATION_ERROR = 'SET_PROJECT_REPRESENTATION_ERROR'

// Roster
export const GET_ROSTER = 'GET_ROSTER'
export const POST_ROSTER = 'POST_ROSTER'
export const PUT_ROSTER = 'PUT_ROSTER'
export const DELETE_ROSTER = 'DELETE_ROSTER'
export const SUCCESS_ROSTER = 'SUCCESS_ROSTER'
export const ERROR_ROSTER = 'ERROR_ROSTER'

// CONSTANT
export const GET_CONSTANT = 'GET_CONSTANT'
export const POST_CONSTANT = 'POST_CONSTANT'
export const PUT_CONSTANT = 'PUT_CONSTANT'
export const DELETE_CONSTANT = 'DELETE_CONSTANT'
export const SUCCESS_CONSTANT = 'SUCCESS_CONSTANT'
export const ERROR_CONSTANT = 'ERROR_CONSTANT'

// Levy CATEGORY Start
export const GET_LEVYCATEGORY = 'GET_LEVYCATEGORY'
export const GET_LEVYCATEGORY_OPTION = 'GET_LEVYCATEGORY_OPTION'
export const POST_LEVYCATEGORY = 'POST_LEVYCATEGORY'
export const PUT_LEVYCATEGORY = 'PUT_LEVYCATEGORY'
export const DELETE_LEVYCATEGORY = 'DELETE_LEVYCATEGORY'
export const SUCCESS_LEVYCATEGORY = 'SUCCESS_LEVYCATEGORY'
export const ERROR_LEVYCATEGORY = 'ERROR_LEVYCATEGORY'

// Levy CATEGORY End

//Levies start

export const GET_LEVY = 'GET_LEVY'
export const POST_LEVY = 'POST_LEVY'
export const PUT_LEVY = 'PUT_LEVY'
export const DELETE_LEVY = 'DELETE_LEVY'
export const SUCCESS_LEVY = 'SUCCESS_LEVY'
export const ERROR_LEVY = 'ERROR_LEVY'

//Levies end
export const PUT_PROJECT_REPRESENTATION_CALENDAR = 'PUT_PROJECT_REPRESENTATION_CALENDAR'
export const PUT_PROJECT_REPRESENTATION_CALENDAR_SUCCESS =
  'PUT_PROJECT_REPRESENTATION_CALENDAR_SUCCESS'
export const PUT_PROJECT_REPRESENTATION_CALENDAR_ERROR = 'PUT_PROJECT_REPRESENTATION_CALENDAR_ERROR'

export const DELETE_PROJECT_REPRESENTATION_CALENDAR = 'DELETE_PROJECT_REPRESENTATION_CALENDAR'
export const DELETE_PROJECT_REPRESENTATION_CALENDAR_SUCCESS =
  'DELETE_PROJECT_REPRESENTATION_CALENDAR_SUCCESS'
export const DELETE_PROJECT_REPRESENTATION_CALENDAR_ERROR =
  'DELETE_PROJECT_REPRESENTATION_CALENDAR_ERROR'

export const PUT_PERIOD_SHORTEN = 'PUT_PERIOD_SHORTEN'
export const PUT_PERIOD_SHORTEN_SUCCESS = 'PUT_PERIOD_SHORTEN_SUCCESS'
export const PUT_PERIOD_SHORTEN_ERROR = 'PUT_PERIOD_SHORTEN_ERROR'

export const PUT_PERIOD_EXTEND = 'PUT_PERIOD_EXTEND'
export const PUT_PERIOD_EXTEND_SUCCESS = 'PUT_PERIOD_EXTEND_SUCCESS'
export const PUT_PERIOD_EXTEND_ERROR = 'PUT_PERIOD_EXTEND_ERROR'

export const PUT_PERIOD_CUSTOM = 'PUT_PERIOD_CUSTOM'
export const PUT_PERIOD_CUSTOM_SUCCESS = 'PUT_PERIOD_CUSTOM_SUCCESS'
export const PUT_PERIOD_CUSTOM_ERROR = 'PUT_PERIOD_CUSTOM_ERROR'

export const PUT_PERIOD_EDIT_DATE = 'PUT_PERIOD_EDIT_DATE'
export const PUT_PERIOD_EDIT_DATE_SUCCESS = 'PUT_PERIOD_EDIT_DATE_SUCCESS'
export const PUT_PERIOD_EDIT_DATE_ERROR = 'PUT_PERIOD_EDIT_DATE_ERROR'

// cost indices
export const GET_COST_INDICES = 'GET_COST_INDICES'
export const GET_COST_INDICES_SUCCESS = 'GET_COST_INDICES_SUCCESS'
export const GET_COST_INDICES_ERROR = 'GET_COST_INDICES_ERROR'

export const POST_COST_INDICES = 'POST_COST_INDICES'
export const POST_COST_INDICES_SUCCESS = 'POST_COST_INDICES_SUCCESS'
export const POST_COST_INDICES_ERROR = 'POST_COST_INDICES_ERROR'

export const PUT_COST_INDICES = 'PUT_COST_INDICES'
export const PUT_COST_INDICES_SUCCESS = 'PUT_COST_INDICES_SUCCESS'
export const PUT_COST_INDICES_ERROR = 'PUT_COST_INDICES_ERROR'

export const DELETE_COST_INDICES = 'DELETE_COST_INDICES'
export const DELETE_COST_INDICES_SUCCESS = 'DELETE_COST_INDICES_SUCCESS'
export const DELETE_COST_INDICES_ERROR = 'DELETE_COST_INDICES_ERROR'

// exchange rate
export const GET_EXCHANGE_RATE = 'GET_EXCHANGE_RATE'
export const GET_EXCHANGE_RATE_SUCCESS = 'GET_EXCHANGE_RATE_SUCCESS'
export const GET_EXCHANGE_RATE_ERROR = 'GET_EXCHANGE_RATE_ERROR'

export const POST_EXCHANGE_RATE = 'POST_EXCHANGE_RATE'
export const POST_EXCHANGE_RATE_SUCCESS = 'POST_EXCHANGE_RATE_SUCCESS'
export const POST_EXCHANGE_RATE_ERROR = 'POST_EXCHANGE_RATE_ERROR'

export const PUT_EXCHANGE_RATE = 'PUT_EXCHANGE_RATE'
export const PUT_EXCHANGE_RATE_SUCCESS = 'PUT_EXCHANGE_RATE_SUCCESS'
export const PUT_EXCHANGE_RATE_ERROR = 'PUT_EXCHANGE_RATE_ERROR'

export const DELETE_EXCHANGE_RATE = 'DELETE_EXCHANGE_RATE'
export const DELETE_EXCHANGE_RATE_SUCCESS = 'DELETE_EXCHANGE_RATE_SUCCESS'
export const DELETE_EXCHANGE_RATE_ERROR = 'DELETE_EXCHANGE_RATE_ERROR'

// Resources - Materials & Services
export const GET_MATERIALS = 'GET_MATERIALS'
export const GET_MATERIALS_SUCCESS = 'GET_MATERIALS_SUCCESS'
export const GET_MATERIALS_ERROR = 'GET_MATERIALS_ERROR'

export const POST_MATERIALS = 'POST_MATERIALS'
export const POST_MATERIALS_SUCCESS = 'POST_MATERIALS_SUCCESS'
export const POST_MATERIALS_ERROR = 'POST_MATERIALS_ERROR'

export const PUT_MATERIALS = 'PUT_MATERIALS'
export const PUT_MATERIALS_SUCCESS = 'PUT_MATERIALS_SUCCESS'
export const PUT_MATERIALS_ERROR = 'PUT_MATERIALS_ERROR'

export const DELETE_MATERIALS = 'DELETE_MATERIALS'
export const DELETE_MATERIALS_SUCCESS = 'DELETE_MATERIALS_SUCCESS'
export const DELETE_MATERIALS_ERROR = 'DELETE_MATERIALS_ERROR'

// Resources - EmployeeType
export const GET_EMPLOYEE_TYPE = 'GET_EMPLOYEE_TYPE'
export const GET_EMPLOYEE_TYPE_SUCCESS = 'GET_EMPLOYEE_TYPE_SUCCESS'
export const GET_EMPLOYEE_TYPE_ERROR = 'GET_EMPLOYEE_TYPE_ERROR'

export const POST_EMPLOYEE_TYPE = 'POST_EMPLOYEE_TYPE'
export const POST_EMPLOYEE_TYPE_SUCCESS = 'POST_EMPLOYEE_TYPE_SUCCESS'
export const POST_EMPLOYEE_TYPE_ERROR = 'POST_EMPLOYEE_TYPE_ERROR'

export const PUT_EMPLOYEE_TYPE = 'PUT_EMPLOYEE_TYPE'
export const PUT_EMPLOYEE_TYPE_SUCCESS = 'PUT_EMPLOYEE_TYPE_SUCCESS'
export const PUT_EMPLOYEE_TYPE_ERROR = 'PUT_EMPLOYEE_TYPE_ERROR'

export const DELETE_EMPLOYEE_TYPE = 'DELETE_EMPLOYEE_TYPE'
export const DELETE_EMPLOYEE_TYPE_SUCCESS = 'DELETE_EMPLOYEE_TYPE_SUCCESS'
export const DELETE_EMPLOYEE_TYPE_ERROR = 'DELETE_EMPLOYEE_TYPE_ERROR'

// Resources - Equipment (Fleet)
export const GET_FLEETS = 'GET_FLEETS'
export const GET_FLEETS_SUCCESS = 'GET_FLEETS_SUCCESS'
export const GET_FLEETS_ERROR = 'GET_FLEETS_ERROR'

export const POST_FLEETS = 'POST_FLEETS'
export const POST_FLEETS_SUCCESS = 'POST_FLEETS_SUCCESS'
export const POST_FLEETS_ERROR = 'POST_FLEETS_ERROR'

export const PUT_FLEETS = 'PUT_FLEETS'
export const PUT_FLEETS_SUCCESS = 'PUT_FLEETS_SUCCESS'
export const PUT_FLEETS_ERROR = 'PUT_FLEETS_ERROR'

export const DELETE_FLEETS = 'DELETE_FLEETS'
export const DELETE_FLEETS_SUCCESS = 'DELETE_FLEETS_SUCCESS'
export const DELETE_FLEETS_ERROR = 'DELETE_FLEETS_ERROR'

export const GET_FLEET_MATERIAL_SERVICE = 'GET_FLEET_MATERIAL_SERVICE'
export const GET_FLEET_MATERIAL_SERVICE_SUCCESS = 'GET_FLEET_MATERIAL_SERVICE_SUCCESS'
export const GET_FLEET_MATERIAL_SERVICE_ERROR = 'GET_FLEET_MATERIAL_SERVICE_ERROR'

// Resources - Infrastructure
export const GET_INFRASTRUCTURE = 'GET_INFRASTRUCTURE'
export const GET_INFRASTRUCTURE_SUCCESS = 'GET_INFRASTRUCTURE_SUCCESS'
export const GET_INFRASTRUCTURE_ERROR = 'GET_INFRASTRUCTURE_ERROR'

export const POST_INFRASTRUCTURE = 'POST_INFRASTRUCTURE'
export const POST_INFRASTRUCTURE_SUCCESS = 'POST_INFRASTRUCTURE_SUCCESS'
export const POST_INFRASTRUCTURE_ERROR = 'POST_INFRASTRUCTURE_ERROR'

export const PUT_INFRASTRUCTURE = 'PUT_INFRASTRUCTURE'
export const PUT_INFRASTRUCTURE_SUCCESS = 'PUT_INFRASTRUCTURE_SUCCESS'
export const PUT_INFRASTRUCTURE_ERROR = 'PUT_INFRASTRUCTURE_ERROR'

export const DELETE_INFRASTRUCTURE = 'DELETE_INFRASTRUCTURE'
export const DELETE_INFRASTRUCTURE_SUCCESS = 'DELETE_INFRASTRUCTURE_SUCCESS'
export const DELETE_INFRASTRUCTURE_ERROR = 'DELETE_INFRASTRUCTURE_ERROR'

export const PUT_INDEX_ALLOCATION = 'PUT_INDEX_ALLOCATION'
export const PUT_INDEX_ALLOCATION_SUCCESS = 'PUT_INDEX_ALLOCATION_SUCCESS'
export const PUT_INDEX_ALLOCATION_ERROR = 'PUT_INDEX_ALLOCATION_ERROR'

// equipment cost centre start
export const GET_EQUIPMENTCC = 'GET_EQUIPMENTCC'
export const POST_EQUIPMENTCC = 'POST_EQUIPMENTCC'
export const PUT_EQUIPMENTCC = 'PUT_EQUIPMENTCC'
export const DELETE_EQUIPMENTCC = 'DELETE_EQUIPMENTCC'
export const SUCCESS_EQUIPMENTCC = 'SUCCESS_EQUIPMENTCC'
export const ERROR_EQUIPMENTCC = 'ERROR_EQUIPMENTCC'
// equipment cost centre end

// personel cost centre start
export const GET_PERSONELCC = 'GET_PERSONELCC'
export const POST_PERSONELCC = 'POST_PERSONELCC'
export const PUT_PERSONELCC = 'PUT_PERSONELCC'
export const DELETE_PERSONELCC = 'DELETE_PERSONELCC'
export const SUCCESS_PERSONELCC = 'SUCCESS_PERSONELCC'
export const ERROR_PERSONELCC = 'ERROR_PERSONELCC'
// equipment cost centre end

// material and  service cost center start

export const GET_MATERIALCC = 'GET_MATERIALCC'
export const POST_MATERIALCC = 'POST_MATERIALCC'
export const PUT_MATERIALCC = 'PUT_MATERIALCC'
export const DELETE_MATERIALCC = 'DELETE_MATERIALCC'
export const SUCCESS_MATERIALCC = 'SUCCESS_MATERIALCC'
export const ERROR_MATERIALCC = 'ERROR_MATERIALCC'

// material and service cost center end

// cost centre Infrastructure start
export const GET_INFRASTRUCTURECC = 'GET_INFRASTRUCTURECC'
export const POST_INFRASTRUCTURECC = 'POST_INFRASTRUCTURECC'
export const PUT_INFRASTRUCTURECC = 'PUT_INFRASTRUCTURECC'
export const DELETE_INFRASTRUCTURECC = 'DELETE_INFRASTRUCTURECC'
export const SUCCESS_INFRASTRUCTURECC = 'SUCCESS_INFRASTRUCTURECC'
export const ERROR_INFRASTRUCTURECC = 'ERROR_INFRASTRUCTURECC'
// cost centre Infrastructure end
export const GET_COST_CENTRE = 'GET_COST_CENTRE'
export const GET_COST_CENTRE_SUCCESS = 'GET_COST_CENTRE_SUCCESS'
export const GET_COST_CENTRE_ERROR = 'GET_COST_CENTRE_ERROR'

export const POST_COST_CENTRE = 'POST_COST_CENTRE'
export const POST_COST_CENTRE_SUCCESS = 'POST_COST_CENTRE_SUCCESS'
export const POST_COST_CENTRE_ERROR = 'POST_COST_CENTRE_ERROR'

export const PUT_COST_CENTRE = 'PUT_COST_CENTRE'
export const PUT_COST_CENTRE_SUCCESS = 'PUT_COST_CENTRE_SUCCESS'
export const PUT_COST_CENTRE_ERROR = 'PUT_COST_CENTRE_ERROR'

export const DELETE_COST_CENTRE = 'DELETE_COST_CENTRE'
export const DELETE_COST_CENTRE_SUCCESS = 'DELETE_COST_CENTRE_SUCCESS'
export const DELETE_COST_CENTRE_ERROR = 'DELETE_COST_CENTRE_ERROR'

// equipment schedule OH Function start

export const GET_EQUIPMENTSCHEDULEOH = 'GET_EQUIPMENTSCHEDULEOH'
export const POST_EQUIPMENTSCHEDULEOH = 'POST_EQUIPMENTSCHEDULEOH'
export const PUT_EQUIPMENTSCHEDULEOH = 'PUT_EQUIPMENTSCHEDULEOH'
export const DELETE_EQUIPMENTSCHEDULEOH = 'DELETE_EQUIPMENTSCHEDULEOH'
export const SUCCESS_EQUIPMENTSCHEDULEOH = 'SUCCESS_EQUIPMENTSCHEDULEOH'
export const ERROR_EQUIPMENTSCHEDULEOH = 'ERROR_EQUIPMENTSCHEDULEOH'

// equipment schedule OH Function end

// user start
export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const UPLOAD_FILE = 'UPLOAD_FILE'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR'

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR'

export const UPDATE_ROLE = 'UPDATE_ROLE'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_ERROR = 'UPDATE_ROLE_ERROR'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR'

export const POST_USER = 'POST_USER'
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS'
export const POST_USER_ERROR = 'POST_USER_ERROR'

export const PUT_USER = 'PUT_USER'
export const PUT_USER_SUCCESS = 'PUT_USER_SUCCESS'
export const PUT_USER_ERROR = 'PUT_USER_ERROR'

export const DELETE_USER = 'DELETE_USER'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'
// user end

// company start
export const GET_COMPANY = 'GET_COMPANY'
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS'
export const GET_COMPANY_ERROR = 'GET_COMPANY_ERROR'

export const POST_COMPANY = 'POST_COMPANY'
export const POST_COMPANY_SUCCESS = 'POST_COMPANY_SUCCESS'
export const POST_COMPANY_ERROR = 'POST_COMPANY_ERROR'

export const PUT_COMPANY = 'PUT_COMPANY'
export const PUT_COMPANY_SUCCESS = 'PUT_COMPANY_SUCCESS'
export const PUT_COMPANY_ERROR = 'PUT_COMPANY_ERROR'

export const DELETE_COMPANY = 'DELETE_COMPANY'
export const DELETE_COMPANY_SUCCESS = 'DELETE_COMPANY_SUCCESS'
export const DELETE_COMPANY_ERROR = 'DELETE_COMPANY_ERROR'
// company end

// role start
export const GET_ROLE = 'GET_ROLE'
export const GET_ROLE_SUCCESS = 'GET_ROLE_SUCCESS'
export const GET_ROLE_ERROR = 'GET_ROLE_ERROR'

export const POST_ROLE = 'POST_ROLE'
export const POST_ROLE_SUCCESS = 'POST_ROLE_SUCCESS'
export const POST_ROLE_ERROR = 'POST_ROLE_ERROR'

export const PUT_ROLE = 'PUT_ROLE'
export const PUT_ROLE_SUCCESS = 'PUT_ROLE_SUCCESS'
export const PUT_ROLE_ERROR = 'PUT_ROLE_ERROR'

export const DELETE_ROLE = 'DELETE_ROLE'
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR'
// role end

export const GET_EQUIPMENT_TYPES = 'GET_EQUIPMENT_TYPES'

// Start Production
export const GET_PRODUCTION_SCHEDULE = 'GET_PRODUCTION_SCHEDULE'
export const GET_PRODUCTION_SCHEDULE_SUCCESS = 'GET_PRODUCTION_SCHEDULE_SUCCESS'
export const GET_PRODUCTION_SCHEDULE_ERROR = 'GET_PRODUCTION_SCHEDULE_ERROR'

export const POST_PRODUCTION_SCHEDULE = 'POST_PRODUCTION_SCHEDULE'
export const POST_PRODUCTION_SCHEDULE_SUCCESS = 'POST_PRODUCTION_SCHEDULE_SUCCESS'
export const POST_PRODUCTION_SCHEDULE_ERROR = 'POST_PRODUCTION_SCHEDULE_ERROR'

export const PUT_PRODUCTION_SCHEDULE = 'PUT_PRODUCTION_SCHEDULE'
export const PUT_PRODUCTION_SCHEDULE_SUCCESS = 'PUT_PRODUCTION_SCHEDULE_SUCCESS'
export const PUT_PRODUCTION_SCHEDULE_ERROR = 'PUT_PRODUCTION_SCHEDULE_ERROR'

export const DELETE_PRODUCTION_SCHEDULE = 'DELETE_PRODUCTION_SCHEDULE'
export const DELETE_PRODUCTION_SCHEDULE_SUCCESS = 'DELETE_PRODUCTION_SCHEDULE_SUCCESS'
export const DELETE_PRODUCTION_SCHEDULE_ERROR = 'DELETE_PRODUCTION_SCHEDULE_ERROR'

export const GET_PRODUCTION_FACTOR = 'GET_PRODUCTION_FACTOR'
export const GET_PRODUCTION_FACTOR_SUCCESS = 'GET_PRODUCTION_FACTOR_SUCCESS'
export const GET_PRODUCTION_FACTOR_ERROR = 'GET_PRODUCTION_FACTOR_ERROR'

export const POST_PRODUCTION_FACTOR = 'POST_PRODUCTION_FACTOR'
export const POST_PRODUCTION_FACTOR_SUCCESS = 'POST_PRODUCTION_FACTOR_SUCCESS'
export const POST_PRODUCTION_FACTOR_ERROR = 'POST_PRODUCTION_FACTOR_ERROR'

export const PUT_PRODUCTION_FACTOR = 'PUT_PRODUCTION_FACTOR'
export const PUT_PRODUCTION_FACTOR_SUCCESS = 'PUT_PRODUCTION_FACTOR_SUCCESS'
export const PUT_PRODUCTION_FACTOR_ERROR = 'PUT_PRODUCTION_FACTOR_ERROR'

export const DELETE_PRODUCTION_FACTOR = 'DELETE_PRODUCTION_FACTOR'
export const DELETE_PRODUCTION_FACTOR_SUCCESS = 'DELETE_PRODUCTION_FACTOR_SUCCESS'
export const DELETE_PRODUCTION_FACTOR_ERROR = 'DELETE_PRODUCTION_FACTOR_ERROR'
// END Production

// EQUIPMENT_ROSTER start
export const GET_EQUIPMENT_ROSTER = 'GET_EQUIPMENT_ROSTER'
export const GET_EQUIPMENT_ROSTER_SUCCESS = 'GET_EQUIPMENT_ROSTER_SUCCESS'
export const GET_EQUIPMENT_ROSTER_ERROR = 'GET_EQUIPMENT_ROSTER_ERROR'

export const POST_EQUIPMENT_ROSTER = 'POST_EQUIPMENT_ROSTER'
export const POST_EQUIPMENT_ROSTER_SUCCESS = 'POST_EQUIPMENT_ROSTER_SUCCESS'
export const POST_EQUIPMENT_ROSTER_ERROR = 'POST_EQUIPMENT_ROSTER_ERROR'
// EQUIPMENT_ROSTER end

// EQUIPMENT_PA start
export const GET_EQUIPMENT_PA = 'GET_EQUIPMENT_PA'
export const GET_EQUIPMENT_PA_SUCCESS = 'GET_EQUIPMENT_PA_SUCCESS'
export const GET_EQUIPMENT_PA_ERROR = 'GET_EQUIPMENT_PA_ERROR'

export const POST_EQUIPMENT_PA = 'POST_EQUIPMENT_PA'
export const POST_EQUIPMENT_PA_SUCCESS = 'POST_EQUIPMENT_PA_SUCCESS'
export const POST_EQUIPMENT_PA_ERROR = 'POST_EQUIPMENT_PA_ERROR'
// EQUIPMENT_PA end
